version: 0.2

phases:
  install:
    commands:
      - curl -o- -L https://yarnpkg.com/install.sh | bash
  pre_build:
    commands:
      - ~/.yarn/bin/yarn --ignore-engines
  build:
    commands:
      - ~/.yarn/bin/yarn prod
  post_build:
    commands:
      - echo "******** Uploading to S3 ********"
      - aws s3 sync public/ s3://guitar-scales
      - aws s3 cp public/index.html s3://guitar-scales/index.html --cache-control max-age=0